// <auto-generated />
using System;
using FlashGamingHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashGamingHub.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240528183003_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlashGamingHub.Models.Community", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"), 1L, 1);

                    b.Property<bool>("ActiveMember")
                        .HasColumnType("bit");

                    b.Property<int?>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("GameID");

                    b.HasIndex("UserID");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            MessageID = 1,
                            ActiveMember = true,
                            GameID = 1,
                            LikesCount = 100,
                            Message = "Community1",
                            PublicationDate = new DateTime(2023, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3640),
                            UserID = 1
                        },
                        new
                        {
                            MessageID = 2,
                            ActiveMember = true,
                            GameID = 1,
                            LikesCount = 150,
                            Message = "Community2",
                            PublicationDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3643),
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"), 1L, 1);

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.Property<int>("StudioID")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("GameID");

                    b.HasIndex("StoreID");

                    b.HasIndex("StudioID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            Categories = "Fighting, Action, Violent",
                            Description = "32 fighters with next-gen visuals will collide in Tekken 8! Both new and returning characters are stunningly portrayed in high-detailed character models built from the ground up - featuring every drop of sweat and ripped muscles for an immersive experience. The roster includes iconic fighters like Paul Phoenix, King, Marshall Law, and Nina Williams, and sees the return of Raven after last being part of the story of Tekken 6, 15 years ago! Jun Kazama returns to the story for the first time in 25 years since her disappearance in Tekken 2, and Tekken 8 also introduces a new Peruvian character Azucena! Players will be able to challenge their opponents on 16 battle stages with intense destruction and interactive stage elements.",
                            Discount = 0,
                            Name = "Tekken 8",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2023, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3566),
                            StoreID = 1,
                            StudioID = 1,
                            Synopsis = "TEKKEN 8 continues the tragic saga of the Mishima bloodline and its world-shaking father-and-son grudge matches. After defeating his father, Heihachi Mishima, Kazuya continues his conquest for global domination, using the forces of G Corporation to wage war on the world."
                        },
                        new
                        {
                            GameID = 2,
                            Categories = "Role-Playing (RPG), Open World, Graphic Adventure",
                            Description = "Journey through the Lands Between, a new fantasy world created by Hidetaka Miyazaki, creator of the influential DARK SOULS video game series, and George R. R. Martin, author of The New York Times best-selling fantasy series, A Song of Ice and Fire.Unravel the mysteries of the Elden Ring’s power. Encounter adversaries with profound backgrounds, characters with their own unique motivations for helping or hindering your progress, and fearsome creatures.Create your character in FromSoftware's refined action-RPG and define your playstyle by experimenting with a wide variety of weapons, magical abilities, and skills found throughout the world. Charge into battle, pick off enemies one-by-one using stealth, or even call upon allies for aid. Many options are at your disposal as you decide how to approach exploration and combat.",
                            Discount = 0,
                            Name = "Elden Ring",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3570),
                            StoreID = 1,
                            StudioID = 1,
                            Synopsis = "Marika's offspring, demigods all, claimed the shards of the Elden Ring known as the Great Runes, and the mad taint of their newfound strength triggered a war: The Shattering. A war that meant abandonment by the Greater Will."
                        },
                        new
                        {
                            GameID = 3,
                            Categories = "Role-Playing (RPG), Open World, Graphic Adventure, Action",
                            Description = "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades. The relationships you forge and the choices you make will shape the story and the world around you.",
                            Discount = 50,
                            Name = "Ciberpunk 2077",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3573),
                            StoreID = 1,
                            StudioID = 1,
                            Synopsis = "Become an urban outlaw equipped with cybernetic enhancements and build your legend on the streets of Night City. Night City is packed to the brim with things to do, places to see, and people to meet. And it’s up to you where to go, when to go, and how to get there."
                        },
                        new
                        {
                            GameID = 4,
                            Categories = "Role-Playing (RPG), Open World, Graphic Adventure, Fantasy",
                            Description = "Built for endless adventure, the massive open world of The Witcher sets new standards in terms of size, depth, and complexity. - Traverse a fantastical open world: explore forgotten ruins, caves, and shipwrecks, trade with merchants and dwarven smiths in cities, and hunt across the open plains, mountains, and seas. - Deal with treasonous generals, devious witches, and corrupt royalty to provide dark and dangerous services. - Make choices that go beyond good & evil, and face their far-reaching consequences.",
                            Discount = 20,
                            Name = "The Witcher 3: The Wild Hunt",
                            Price = 62.97m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3576),
                            StoreID = 1,
                            StudioID = 1,
                            Synopsis = "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world."
                        },
                        new
                        {
                            GameID = 5,
                            Categories = "Action, Open World, Adventure, Anime, Fighting",
                            Description = "Experience the story of DRAGON BALL Z from epic events to light-hearted side quests, including never-before-seen story moments that answer some burning questions of Dragon Ball lore for the first time! Play through iconic DRAGON BALL Z battles on a scale unlike any other. Fight across vast battlefields with destructible environments and experience epic boss battles that will test the limits of your combat abilities. Increase your power level and rise to the challenge!",
                            Discount = 40,
                            Name = "Dragon Ball Z: Kakarot",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3579),
                            StoreID = 1,
                            StudioID = 1,
                            Synopsis = "Relive the story of Goku in DRAGON BALL Z: KAKAROT! Beyond the epic battles, experience life in the DRAGON BALL Z world as you fight, fish, eat, and train with Goku. Explore the new areas and adventures as you advance through the story and form powerful bonds with other heroes."
                        },
                        new
                        {
                            GameID = 6,
                            Categories = "Action, Adventure, Violent, Stealth",
                            Description = "FIGHT FOR FREEDOM 1775: The American Colonies are about to revolt. As Connor, a Native American Assassin, secure liberty for your people and your nation. From bustling city streets to the chaotic battlefields, assassinate your foes in a variety of deadly ways with a vast array of weaponry. A NEW VISUAL AND GAMEPLAY EXPERIENCE Play the iconic Assassin's Creed III with enhanced graphics, now featuring 4K resolution, new character models, polished environment rendering and more. The gameplay mechanics have been revamped as well, improving your experience and your immersion.",
                            Discount = 7,
                            Name = "Assasins Creed III Remastered",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3582),
                            StoreID = 1,
                            StudioID = 2,
                            Synopsis = "Relive the American Revolution or experience it for the first time in Assassin's Creed III Remastered, with enhanced graphics and improved gameplay mechanics."
                        },
                        new
                        {
                            GameID = 7,
                            Categories = "Action, Violent, Gore, Multiplayer",
                            Description = "When the Cataclysm wreaked havoc on the world, all was lost. The once great order of Knights, whose tales of heroism and gallantry abounded, was razed to the ground. In the wastelands, what survivors remained were hopeless. All scavenged for food and water. And the strong preyed on the weak. But in the gloom of ash, there came a beacon of light: the Unsung Knight. A lone Warden, who made it her mission to help those in need. To use Valor’s Edge, the sword bequeathed unto her, to fight back against pillagers and invaders – and to bring hope to her people. For it was said this legendary sword would one day, in the bleakest of times, unite the Knights once more…",
                            Discount = 5,
                            Name = "For Honor",
                            Price = 29.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3585),
                            StoreID = 1,
                            StudioID = 2,
                            Synopsis = "After a great cataclysm, 4 of the fiercest warrior factions in history clash in an epic battle for survival. Join the war as a bold Knight, brutal Viking, deadly Samurai or fearsome Wu Lin and fight for your faction’s honor."
                        },
                        new
                        {
                            GameID = 8,
                            Categories = "Tactical, Shooter, Violent, Multiplayer",
                            Description = "Siege is an entry in the Rainbow Six series and the successor to Tom Clancy's Rainbow 6: Patriots, a tactical shooter that had a larger focus on narrative. After Patriots was eventually cancelled due to its technical shortcomings, Ubisoft decided to reboot the franchise. The team evaluated the core of the Rainbow Six franchise and believed that letting players impersonate the top counter-terrorist operatives around the world suited the game most. To create authentic siege situations, the team consulted actual counter-terrorism units and looked at real-life examples of sieges such as the 1980 Iranian Embassy siege.",
                            Discount = 0,
                            Name = "Rainbow Six Siege",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3588),
                            StoreID = 1,
                            StudioID = 2,
                            Synopsis = "Tom Clancy's Rainbow Six® Siege is an elite, realistic, tactical team-based shooter where superior planning and execution triumph. It features 5v5 attack vs."
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.GameShop", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"), 1L, 1);

                    b.Property<int>("AnnualSales")
                        .HasColumnType("int");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("StoreID");

                    b.ToTable("GameShops");

                    b.HasData(
                        new
                        {
                            StoreID = 1,
                            AnnualSales = 0,
                            Event = "Summer Discounts",
                            LastUpdated = new DateTime(2024, 4, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3503),
                            Origin = "Europe",
                            Stock = 100
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.LibraryGameUser", b =>
                {
                    b.Property<int>("LibraryGameUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibraryGameUserId"), 1L, 1);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LibraryGameUserId");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("LibraryGameUsers");

                    b.HasData(
                        new
                        {
                            LibraryGameUserId = 1,
                            AddedDate = new DateTime(2023, 11, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3620),
                            HoursPlayed = 50,
                            LastPlayed = new DateTime(2024, 5, 21, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3623),
                            Rating = 4,
                            UserID = 1
                        },
                        new
                        {
                            LibraryGameUserId = 2,
                            AddedDate = new DateTime(2024, 2, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3625),
                            HoursPlayed = 100,
                            LastPlayed = new DateTime(2024, 5, 23, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3628),
                            Rating = 5,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartID"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            ShoppingCartID = 1,
                            FechaCreacion = new DateTime(2024, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3655),
                            Total = 0m,
                            UserID = 1
                        },
                        new
                        {
                            ShoppingCartID = 2,
                            FechaCreacion = new DateTime(2024, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3657),
                            Total = 0m,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.Studio", b =>
                {
                    b.Property<int>("StudioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudioID"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailContact")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fundation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudioID");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            StudioID = 1,
                            Country = "Japan",
                            EmailContact = "bandaisupport@gmail.com",
                            EmailLogin = "bandainamco@gmail.com",
                            Fundation = new DateTime(2014, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3374),
                            Name = "Bandai Namco Entertainment",
                            Password = "Dq61uGd16mtsRoJ.",
                            Website = "www.bandai.com"
                        },
                        new
                        {
                            StudioID = 2,
                            Country = "France",
                            EmailContact = "ubisoftsupport@gmail.com",
                            EmailLogin = "ubisoft@gmail.com",
                            Fundation = new DateTime(2019, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3405),
                            Name = "Ubisoft",
                            Password = "4F1Gb7P72SHlwos",
                            Website = "www.ubisoft.com"
                        },
                        new
                        {
                            StudioID = 3,
                            Country = "Tokyo",
                            EmailContact = "sonysupport@gmail.com",
                            EmailLogin = "sony@gmail.com",
                            Fundation = new DateTime(2019, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3408),
                            Name = "Sony Interactive Entertainment",
                            Password = "7Z94eudXHZLVYYC",
                            Website = "www.sony.com"
                        },
                        new
                        {
                            StudioID = 4,
                            Country = "USA",
                            EmailContact = "activisionsupport@gmail.com",
                            EmailLogin = "activision@gmail.com",
                            Fundation = new DateTime(2019, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3411),
                            Name = "Activision",
                            Password = "2z1K7Fjdno23one",
                            Website = "www.activision.com"
                        });
                });

            modelBuilder.Entity("FlashGamingHub.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LibraryGameUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Age = 30,
                            Email = "admin@gmail.com",
                            LibraryGameUserID = 1,
                            Name = "userAdmin",
                            Password = "L4Mf13z1E7YsU7N",
                            RegisterDate = new DateTime(2022, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3604),
                            Role = "admin",
                            Surname = "surnameAdmin"
                        },
                        new
                        {
                            UserID = 2,
                            Age = 25,
                            Email = "user@gmail.com",
                            LibraryGameUserID = 2,
                            Name = "userName",
                            Password = "R0f86GsPcN2tJQ3",
                            RegisterDate = new DateTime(2023, 5, 28, 20, 30, 2, 875, DateTimeKind.Local).AddTicks(3608),
                            Role = "user",
                            Surname = "userSurname"
                        });
                });

            modelBuilder.Entity("GameLibraryGameUser", b =>
                {
                    b.Property<int>("GamesGameID")
                        .HasColumnType("int");

                    b.Property<int>("LibraryGameUserId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameID", "LibraryGameUserId");

                    b.HasIndex("LibraryGameUserId");

                    b.ToTable("GameLibraryGameUser");
                });

            modelBuilder.Entity("GameShoppingCart", b =>
                {
                    b.Property<int>("GamesGameID")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartID")
                        .HasColumnType("int");

                    b.HasKey("GamesGameID", "ShoppingCartID");

                    b.HasIndex("ShoppingCartID");

                    b.ToTable("GameShoppingCart");
                });

            modelBuilder.Entity("FlashGamingHub.Models.Community", b =>
                {
                    b.HasOne("FlashGamingHub.Models.Game", "Game")
                        .WithMany("messages")
                        .HasForeignKey("GameID");

                    b.HasOne("FlashGamingHub.Models.User", "User")
                        .WithMany("messages")
                        .HasForeignKey("UserID");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashGamingHub.Models.Game", b =>
                {
                    b.HasOne("FlashGamingHub.Models.GameShop", "StoreAvaidable")
                        .WithMany("Games")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashGamingHub.Models.Studio", "Studio")
                        .WithMany("Games")
                        .HasForeignKey("StudioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreAvaidable");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("FlashGamingHub.Models.LibraryGameUser", b =>
                {
                    b.HasOne("FlashGamingHub.Models.User", "User")
                        .WithOne("libraryGameUser")
                        .HasForeignKey("FlashGamingHub.Models.LibraryGameUser", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashGamingHub.Models.ShoppingCart", b =>
                {
                    b.HasOne("FlashGamingHub.Models.User", "User")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("FlashGamingHub.Models.ShoppingCart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameLibraryGameUser", b =>
                {
                    b.HasOne("FlashGamingHub.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashGamingHub.Models.LibraryGameUser", null)
                        .WithMany()
                        .HasForeignKey("LibraryGameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameShoppingCart", b =>
                {
                    b.HasOne("FlashGamingHub.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashGamingHub.Models.ShoppingCart", null)
                        .WithMany()
                        .HasForeignKey("ShoppingCartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashGamingHub.Models.Game", b =>
                {
                    b.Navigation("messages");
                });

            modelBuilder.Entity("FlashGamingHub.Models.GameShop", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FlashGamingHub.Models.Studio", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("FlashGamingHub.Models.User", b =>
                {
                    b.Navigation("ShoppingCart")
                        .IsRequired();

                    b.Navigation("libraryGameUser")
                        .IsRequired();

                    b.Navigation("messages");
                });
#pragma warning restore 612, 618
        }
    }
}
